apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name | quote }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | quote }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ . | quote }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            {{- if eq (get (default dict .Values.podAnnotations) "inject.xfsc.io/enabled") "false" }}
            - name: PREAUTHBRIDGE_NATS_URL
              value: {{ .Values.config.nats.url | quote }}
            - name: PREAUTHBRIDGE_NATS_REQUEST_TIMEOUT
              value: {{ .Values.config.nats.timeoutInSec | quote }}
            - name: PREAUTHBRIDGE_REDIS_HOSTS
              value: {{ .Values.config.database.hosts | quote }}
            - name: PREAUTHBRIDGE_REDIS_ISCLUSTER
              value: {{ .Values.config.database.iscluster | quote }}
            - name: PREAUTHBRIDGE_REDIS_DATABASE
              value: {{ .Values.config.database.db | quote }}
            - name: PREAUTHBRIDGE_REDIS_USERNAME
              value: {{ .Values.config.database.username | quote }}
            - name: PREAUTHBRIDGE_REDIS_PORT
              value: {{ .Values.config.database.port | quote }}
            - name: PREAUTHBRIDGE_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-redis"
                  key: redis-password
            - name: PREAUTHBRIDGE_OAUTH_NAMESPACE
              value: {{ .Values.config.oAuth.namespace | quote }}
            - name: PREAUTHBRIDGE_OAUTH_GROUPID
              value: {{ .Values.config.oAuth.groupid | quote }}
            - name: PREAUTHBRIDGE_OAUTH_ISSUER_KID
              value: {{ .Values.config.oAuth.issuerKid | quote }}
            - name: PREAUTHBRIDGE_WELLKNOWN_JWKS
              value: {{ .Values.config.wellKnown.jwks | quote }}
            - name: PREAUTHBRIDGE_OAUTH_SIGNER_JWKS_URL
              value: {{ .Values.config.oAuth.signerJwksUrl | quote }}
            - name: PREAUTHBRIDGE_OAUTH_CREDENTIALENDPOINT
              value: {{ .Values.config.oAuth.credentialEndpoint | quote }}
            - name: PREAUTHBRIDGE_OAUTH_KEY
              value: {{ .Values.config.oAuth.key | quote }}
            - name: PREAUTHBRIDGE_OAUTH_ENGINE
              value: {{ .Values.config.oAuth.engine | quote }}
            - name: PREAUTHBRIDGE_OAUTH_SIGNER_TOPIC
              value: {{ .Values.config.oAuth.signerTopic | quote }}
            {{- end }}
            {{- if eq (get (default dict .Values.podAnnotations) "inject.xfsc.io/enabled") "true" }}
            - name: PREAUTHBRIDGE_REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-redis-credentials" .Release.Name | quote }}
                  key: username
            - name: PREAUTHBRIDGE_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-redis-credentials" .Release.Name | quote }}
                  key: password
            {{- end }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: PREAUTHBRIDGE_LISTEN_ADDR
              value: {{ .Values.server.http.host | quote }}
            - name: PREAUTHBRIDGE_LISTEN_PORT
              value: {{ .Values.server.http.port | quote }}
            - name: PREAUTHBRIDGE_WELLKNOWNAUTH_GRANT_TYPES_SUPPORTED
              value: "urn:ietf:params:oauth:grant-type:pre-authorized_code"
            - name: PREAUTHBRIDGE_WELLKNOWNAUTH_TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED
              value: "none"
            - name: PREAUTHBRIDGE_WELLKNOWNAUTH_AUTHORIZATION_DETAILS_TYPES_SUPPORTED
              value: "openid_credential"
            - name: PREAUTHBRIDGE_WELLKNOWNAUTH_PRE_AUTHORIZED_GRANT_ANONYMOUS_ACCESS_SUPPORTED
              value: "true"

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.config.servingPort }}
              protocol: TCP

          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          volumeMounts:
            - name: config-volume
              mountPath: /app

      volumes:
        - name: config-volume
          configMap:
            name: "{{ .Release.Name }}-configmap"
