{{- if eq (get (default dict .Values.podAnnotations) "inject.xfsc.io/enabled") "false" }}
apiVersion: resources.xfsc.io/v1alpha1
kind: ResourceClaim
metadata:
  name: {{ printf "%s-redis" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: redis

  providerRef:
    name: {{ .Values.redis.provider | quote }}

  secretRef:
    name: {{ printf "%s-redis-credentials" .Release.Name | quote }}

  parameters:
    database: {{ default 0 .Values.config.database.db }}
    acl:
      keys:
        - {{ printf "%s:*" .Release.Name | quote }}
{{- end }}